- id: anylogic-export
  name: Export AnyLogic model
  description: "Export a standalone AnyLogic model"
  entry: anylogic
  language: python
  # files: .*\.(alp|alpx)$Py # TODO: also needs to trigger for a directory for .alpx
  pass_filenames: false
